In [ ]:
import pandas as pd 
import pyfaidx
import pysam
import os 
import pathlib
from tqdm import tqdm
from helper_functions import *

refdir = "/Volumes/HNSD01/storage/ref"
outdir = "/Volumes/HNSD01/outdir"
gene_list_version = "v0.1"
output_version = "20250918"

k = 24
additional_flanking_size = 100

path_to_main_output = os.path.join(outdir, "k-mer-feature", "data_analysis", output_version)
path_to_02_output = os.path.join(path_to_main_output, 
                                 "02_output")

os.system(f"mkdir -p {path_to_02_output}")

path_to_hg19 = os.path.join(refdir, "hg19.fa")

all_beds = [item for item in pathlib.Path(f"./custom_tss_gene_beds").glob(f"*/{gene_list_version}/biomart/all_genes/promoter_regions_up_1000_down_1000.bed")]
df = pd.DataFrame()
for file in all_beds:
    tmpdf = pd.read_csv(file, sep="\t", header=None)
    df = pd.concat([df, tmpdf], axis=0)
df.columns = ["chrom", "start", "end", "name"]
df["chrom_num"] = df["chrom"].apply(lambda x: int(x.replace("chr", "")))

df = df.drop_duplicates().reset_index(drop=True)
df.sort_values(by=["chrom_num", "start"], inplace=True)
df = df.drop("chrom_num", axis = 1)
df.to_csv(os.path.join(path_to_02_output, "panel.bed"), sep="\t", index=False, header=False)

os.system(f"mkdir -p ./panels")
df.to_csv(os.path.join("./panels", f"panel_{output_version}.bed"), sep="\t", index=False, header=False)

     chrom     start       end                           name
232   chr1  22799239  22801239   chr1_22800239_22800240_EPHB2
90    chr1  26751951  26753951  chr1_26752951_26752952_ARID1A
91    chr1  26763264  26765264  chr1_26764264_26764265_ARID1A
92    chr1  26765269  26767269  chr1_26766269_26766270_ARID1A
93    chr1  26768173  26770173  chr1_26769173_26769174_ARID1A
..     ...       ...       ...                            ...
258  chr20  45811643  45813643  chr20_45812643_45812644_UBE2C
259  chr20  45811657  45813657  chr20_45812657_45812658_UBE2C
260  chr20  45811673  45813673  chr20_45812673_45812674_UBE2C
261  chr20  45812005  45814005  chr20_45813005_45813006_UBE2C
262  chr20  45813409  45815409  chr20_45814409_45814410_UBE2C

[284 rows x 4 columns]